### ISSUE TITLE
Support file handles

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.2#10]
Lua 5.2 exposes `LUA_FILEHANDLE`, `luaL_Stream` and [`luaL_fileresult`](http://www.lua.org/source/5.2/lauxlib.c.html#luaL_fileresult) in `lauxlib.h`

Lua 5.1 has [`LUA_FILEHANDLE` in `lualib.h`](http://www.lua.org/source/5.1/lualib.h.html#LUA_FILEHANDLE), but not `luaL_Stream` (rather, it uses function environments); `luaL_fileresult` was [`pushresult`](http://www.lua.org/source/5.1/liolib.c.html#pushresult) in `liolib.c`.

**Comment by siffiejoe** [comment]
The definition of `luaL_Stream` has been removed from Compat-5.2. Reason is that it is impossible to make it work on LuaJIT. If you can live with LuaJIT raising an error on the first use of a file method and leaking the file pointer, you can add the definition yourself (you need extra code to set up the environments of the userdatas anyway):
```C
#include <lualib.h>    /* for the definition of LUA_FILEHANDLE */
typedef struct {
  FILE *f;
  lua_CFunction closef;
} luaL_Stream;
```

**Comment by hishamhm** [comment]
Maybe `luaL_Stream` support could be inside an `#ifdef` so that it is only disabled when using LuaJIT?

**Comment by siffiejoe** [comment]
LuaJIT can use binary modules compiled for PUC-Rio Lua 5.1, so a check at compile time is insufficient. Also, I suspect that more and more people still using Lua 5.1 do so because of LuaJIT ...
