### ISSUE TITLE
%q in string.format

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.2#13]
In 5.1, only quotes and null are escaped. http://www.lua.org/source/5.1/lstrlib.c.html#addquoted
In 5.2, all control characters are. http://www.lua.org/source/5.2/lstrlib.c.html#addquoted

**Comment by siffiejoe** [comment]
I came across this issue on an unrelated project and found an easy solution. The current implementation should use short escape sequences when possible as well.
