### ISSUE TITLE
Global error handler function using luaL_traceback

### ISSUE THREAD

**Issue by SteelTitanium** [keplerproject/lua-compat-5.2#25]
Hi, I was wondering if it's possible to set a global error handler function for the current Lua state. I want a stack trace to be shown for every context possible. While I *could* modify various parts of the code to accommodate it, It wouldn't look very appealing and I rather not resort to that, unless absolutely necessary. I'm working with a modified version of Lua 5.1.4 with changes and patches to accommodate the project.

**Comment by hishamhm** [comment]
This project exists strictly to add compatibility versions of existing Lua 5.2 functionality, and not any new features. Are you asking for a particular Lua 5.2 feature that is missing from this library?

**Comment by SteelTitanium** [comment]
No actually, I was just wondering if it was possible to do such thing with the C api and the backported function from this project. But if that's out of the scope then I completely understand and sorry for the misunderstanding.

**Comment by hishamhm** [comment]
No worries!
