### ISSUE TITLE
Trying to run test suite is not success

### ISSUE THREAD

**Issue by mcepl** [keplerproject/lua-compat-5.2#26]
Trying to make tests running on openSUSE/Tumbleweed (when building the package for the distribution) and it doesn’t work well. It seems that the documentation is kind of missing, so after plenty of attempts I tried this:
```
 $ ln -srf c-api/compat-5.2.* tests/
 $ gcc -Wall -Wextra $(pkg-config --cflags --libs lua5.1) -O -shared -fPIC \
     -o 51-testmod.so tests/testmod.c
 $ cd tests
 $ lua5.1 test.lua
```
Unfortunately, the result on the terminal is:
```
tests@stitny$ LANG=en_GB lua5.1 test.lua 
hello world
sh: no_such_file: command not found
hello world
###  no 51-testmod.so or 51-testmod.dll!  ###
'require' claimed: error loading module '51-testmod' from file '../51-testmod.so':
	../51-testmod.so: undefined symbol: lua_absindex
###         Skipping C API tests!         ###
###  Output written to output_Lua51.txt!  ###
tests@stitny$ 
```
and [output_Lua51.txt](https://github.com/keplerproject/lua-compat-5.2/files/5197873/output_Lua51.txt) is not much encouraging either.

Of course, ``/usr/bin/sh`` is in ``$PATH``. Where does ``lua_absindex`` comes from?

What do I do wrong?

**Comment by siffiejoe** [comment]
It looks like you didn't link the compatibility code. This module is quite old. Maybe you should switch to the successor (lua-compat-5.3). However, here is how I build and run the tests (maybe you have to replace the Lua include paths):
```sh
#!/bin/bash -e
echo "Compiling for Lua 5.1 ..."
gcc -Wall -Wextra -Wfatal-errors -O2 -I/usr/include/lua5.1 -I../c-api -fpic -shared -o 51-testmod.so testmod.c ../c-api/compat-5.2.c
echo "Compiling for Lua 5.2 ..."
gcc -Wall -Wextra -Wfatal-errors -O2 -I/usr/include/lua5.2 -I../c-api -fpic -shared -o 52-testmod.so testmod.c ../c-api/compat-5.2.c
#echo "Compiling for Lua 5.0 (object file only) ..."
#gcc -Wall -Wextra -Wfatal-errors -O2 -I/home/siffiejoe/downloads/lua-5.0.3/include -I../c-api -fpic -c -o compat-5.2.o ../c-api/compat-5.2.c
rm -f compat-5.2.o
lua5.1 test.lua
lua5.2 test.lua
echo "To clean up type:"
echo rm -f *.so output_Lua5*.txt
exit 0
```
Then I compare the resulting output files of Lua 5.1 and 5.2 using vimdiff (or similar). They should be nearly identical except for error messages/stack traces and concrete byte numbers reported by the garbage collector API.

**Comment by mcepl** [comment]
Yes, this works. Thank you.
